<?php

namespace Vanguard;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

class Call extends Model
{
    use HasFactory;

    protected $table = 'call';

    protected $fillable = [
        'uuid',
        'phone_contacts',
        'nomer2',
        'phone_contacts2',
        'partner',
        'price_partner',
        'unique_call',
        'title_time',
        'info_data',
        'start',
        'end',
        'destination_number',
        'time_call',
        'user_talk_time',
        'download',
        'calendarId',
        'sms',
        'sms_text',
        'sms_data',
        'send_SMS',
        'hangup_cause',
        'accountcode',
        'gateway',
        'start_stamp',
        'end_stamp',
        'type',
        'user',
        'status_calendarId', //statusID
        'location',
        'comment',
        'commentManager',
        'start_data',
        'end_data',
        'floor',
        'entrance',
        'm2',
        'm2_price',
        'thickness',
        'km',
        'increased',
        'ruchnaya_price',
        'through_entrance',
        'selectOtkaz',
        'selectAdditionalSales',
        'price_styazhka',
        'price',
        'zamer',
        'urgent',
        'setka',
        'setka_m2',
        'setka_cell',
        'setka_who',
        'setka_price_m2',
        'setka_price_all',
        'combine',
        'contract',
        'BN',
        'elevator',
        'source_client', //sourceClient
        'notifications',
        'deals',
        'leads'
    ];

    /*
    protected $fillable = [
        'uuid',
        'phoneContacts',
        'nomer2',
        'phoneContacts2',
        'partner',
        'price_partner',
        'uniqueCall',
        'title_time',
        'info_data',
        'start',
        'end',
        'destination_number',
        'time_call',
        'user_talk_time',
        'download',
        'calendarId',
        'sms',
        'sms_text',
        'sms_data',
        'send_SMS',
        'hangup_cause',
        'accountcode',
        'gateway',
        'start_stamp',
        'end_stamp',
        'type',
        'user',
        'statusID',
        'location',
        'comment',
        'start_data',
        'end_data',
        'floor',
        'entrance',
        'm2',
        'm2_price',
        'thickness',
        'km',
        'increased',
        'ruchnaya_price',
        'through_entrance',
        'selectOtkaz',
        'selectAdditionalSales',
        'price_styazhka',
        'price',
        'zamer',
        'urgent',
        'setka',
        'setka_m2',
        'setka_cell',
        'setka_who',
        'setka_price_m2',
        'setka_price_all',
        'combine',
        'contract',
        'BN',
        'elevator',
        'sourceClient',
        'notifications',
        'deals',
        'leads'
    ];
    */
}